# Generated by Django 2.1.1 on 2018-09-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=255)),
                ('type', models.CharField(default=' ', max_length=255)),
                ('roaster', models.CharField(default=' ', max_length=255)),
                ('country', models.CharField(default=' ', max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('grower', models.CharField(blank=True, max_length=255)),
                ('process', models.CharField(blank=True, max_length=255)),
                ('tasting', jsonfield.fields.JSONField(null=True)),
                ('shopURL', models.URLField(blank=True, max_length=255)),
                ('last_in', models.DateField(null=True)),
                ('next_in', models.DateField(null=True)),
                ('location', jsonfield.fields.JSONField(null=True)),
                ('images', jsonfield.fields.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffees', models.ManyToManyField(blank=True, null=True, related_name='list', to='api.Coffee')),
                ('favourites', models.ManyToManyField(blank=True, null=True, related_name='favourite', to='api.Coffee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
