# Generated by Django 2.1.1 on 2018-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roaster',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
