# Generated by Django 2.1.1 on 2018-09-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='images',
        ),
    ]
