# Generated by Django 2.1.1 on 2018-10-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180922_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='last_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='next_in',
            field=models.DateTimeField(null=True),
        ),
    ]
