# Generated by Django 2.1.1 on 2018-09-05 16:50

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180905_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='images',
            field=jsonfield.fields.JSONField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='location',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='example', max_length=255),
            preserve_default=False,
        ),
    ]
